### ISSUE TITLE
Fix letsencrypt support

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [HackSoftware/cookiecutter-django-ansible#31]

**Comment by jaywink** [comment]
There is a new [ansible-letsencrypt](https://github.com/jaywink/ansible-letsencrypt) version coming which has quite a bit of improvements - will try to push it out tomorrow, sorry for the delay!

**Comment by Ivaylo-Bachvarov** [comment]
Hey,

I am not exactly sure why it is not working. I will take a look tomorrow and leave a issue if I found the problem. 

:beers:

**Comment by jaywink** [comment]
Well, at least [this](https://github.com/HackSoftware/cookiecutter-django-ansible/blob/master/%7B%7B%20cookiecutter.ansible_project_slug%20%7D%7D/ansible_vars/base.yml#L26) should be a list, so `["nginx"]`. Does that help?

There is still one PR in ansible-letsencrypt waiting to be merged, then a new release will be out.

**Comment by Ivaylo-Bachvarov** [comment]
I will fix this. Thanks!

I sometimes works sometimes not. I will do some research this days.
